---
title: "CART, RF, Boosting"
date: "12/13/2019"
output: pdf_document
---

```{r}
library(dplyr) # data manipulation
library(caTools) # splits
library(ggplot2) # plot graph
library(randomForest) # Random Forest
library(rpart)
library(rpart.plot)
library(caret)
library(lubridate)
library(gbm)
library(boot)
```

```{r}
OSR2 <- function(predictions, test, train) {
  SSE <- sum((test - predictions)^2)
  SST <- sum((test - mean(train))^2)
  r2 <- 1 - SSE/SST
  return(r2)
}
```

```{r}
us <- read.csv("us_suicides_merged_no_na.csv")
```

```{r}
suicide_us <- us %>%  select(year, sex, suicides_no, population, suicides.100k.pop, HDI.for.year, gdp_for_year...., gdp_per_capita...., generation, depression_percentage, drug_death_rate) 
```

```{r}
suicide_us$year <- as.factor(suicide_us$year)
```

```{r}
# split data for us 
set.seed(377)
train.ids_us = sample(nrow(suicide_us), 0.70*nrow(suicide_us))
train_us <- suicide_us[train.ids_us,]
test_us <- suicide_us[-train.ids_us,]
```

## CART

```{r}
set.seed(377)

us_train.cart = train(suicides.100k.pop ~ .,
                   data = train_us,
                   method = "rpart",
                   tuneGrid = data.frame(cp=seq(0, 0.1, 0.001)),
                   trControl = trainControl(method="cv", number=10),
                   metric = "RMSE") 
us_train.cart$bestTune
```

```{r}
ggplot(us_train.cart$results, aes(x=cp, y=RMSE)) + geom_point() 
```

```{r}
us_train.cart$results
```

```{r}
mod.us_cart <- us_train.cart$finalModel
prp(mod.us_cart)
```


```{r}
us_test.cart = as.data.frame(model.matrix(suicides.100k.pop ~ . + 0, data=test_us))

predcart_us = predict(mod.us_cart, newdata=us_test.cart)
#predcart_us$results
cart.tab.us <- table(test_us$suicides.100k.pop, predcart_us)
cart.tab.us
```

```{r}
print("CART OSR2:")
OSR2(predcart_us, test_us$suicides.100k.pop, train_us$suicides.100k.pop)
```


# Random Forest

```{r}
set.seed(377)

mod.rf.us <- randomForest(suicides.100k.pop ~ ., data = train_us, mtry = 5, nodesize = 5, ntree = 500)
```

```{r} 
pred.rf.us <- predict(mod.rf.us, newdata = test_us) # just to illustrate
pred.rf.us[1:5] 
```

```{r}
importance(mod.rf.us)
```

```{r}
set.seed(377)
train.rf.us <- train(suicides.100k.pop ~ .,
                     data = train_us,
                     method = "rf",
                     tuneGrid = data.frame(mtry=1:5),
                     trControl = trainControl(method="cv", number=5, verboseIter = TRUE),
                     metric = "RMSE") 
```

```{r}
train.rf.us$results
```

```{r}
best.rf.us <- train.rf.us$finalModel 
```

```{r}
us.test_rf = as.data.frame(model.matrix(suicides.100k.pop ~ . + 0, data = test_us)) 
```

```{r}
pred.best.rf_us <- predict(best.rf.us, newdata = us.test_rf)
pred.best.rf_us[1:5]
```

```{r}
print("Random Forests OSR2:")
OSR2(pred.best.rf_us, test_us$suicides.100k.pop, train_us$suicides.100k.pop)
```

```{r}
ggplot(train.rf.us$results, aes(x = mtry, y = Rsquared)) + geom_point(size = 3) + 
  ylab("CV Rsquared") + theme_bw() + theme(axis.title=element_text(size=18), axis.text=element_text(size=18))
```

## mtry = 10
```{r}
set.seed(377)
train.rf.us_mtryTen <- train(suicides.100k.pop ~ .,
                             data = train_us,
                             method = "rf",
                             tuneGrid = data.frame(mtry=1:10),
                             trControl = trainControl(method="cv", number=5, verboseIter = TRUE),
                             metric = "RMSE") 
```

```{r}
train.rf.us_mtryTen$results
```

```{r}
best.rf.us_mtryTen <- train.rf.us_mtryTen$finalModel 
```

```{r}
pred.best.rf_us_mtryTen <- predict(best.rf.us_mtryTen, newdata = us.test_rf)
pred.best.rf_us_mtryTen[1:5]
```

```{r}
print("Random Forests OSR2:")
OSR2(pred.best.rf_us_mtryTen, test_us$suicides.100k.pop, train_us$suicides.100k.pop)
```

### Boosting
```{r}
mod.boost <- gbm(suicides.100k.pop ~ .,
                 data = train_us,
                 distribution = "gaussian",
                 n.trees = 1000,
                 shrinkage = 0.001,
                 interaction.depth = 2)
summary(mod.boost)
```

```{r}
pred.boost <- predict(mod.boost, newdata = test_us, n.trees=1000)
OSR2(pred.boost, test_us$suicides.100k.pop, train_us$suicides.100k.pop)
```

```{r}
## took a while to run -- not super amazing OSR^2
# test_us_mm = as.data.frame(model.matrix(suicides.100k.pop ~ . + 0, data = test_us)) 
# 
# gbmGrid <-  expand.grid(interaction.depth = c(1,2,4,6,8,10), 
#                         n.trees = (1:75)*500, 
#                         shrinkage = 0.001,
#                         n.minobsinnode = 10)
# fitControl <- trainControl(## 10-fold CV
#                            method = "repeatedcv",
#                            number = 5,
#                            ## repeated ten times
#                            repeats = 5)
# set.seed(377)
# gbmFit2 <- train(suicides.100k.pop ~ ., data = train_us, 
#                  method = "gbm", 
#                  trControl = fitControl, 
#                  verbose = FALSE, 
#                  tuneGrid = gbmGrid)
# 
# gbm.best <- gbmFit2$finalModel
# gbm.pred.best.boost <- predict(gbm.best, newdata = test_us_mm, n.trees = 11500)
# OSR2(gbm.pred.best.boost, test_us$suicides.100k.pop, train_us$suicides.100k.pop)
```

```{r}
## same results as above
# tGrid = expand.grid(n.trees = 1000, interaction.depth = 2, shrinkage = 0.001, n.minobsinnode = 10)tGrid = expand.grid(n.trees = 1000, interaction.depth = 2, shrinkage = 0.001, n.minobsinnode = 10)
# 
# set.seed(377)
# train.boost <- train(suicides.100k.pop ~ .,
#                      data = train_us,
#                      method = "gbm",
#                      tuneGrid = tGrid,
#                      trControl = trainControl(method="cv", number=5,
#                                               verboseIter = FALSE),
#                      metric = "RMSE",
#                      distribution = "gaussian", 
#                      verbose = FALSE)
# train.boost
# best.boost <- train.boost$finalModel
# pred.best.boost <- predict(best.boost, newdata = test_us_mm, n.trees = 11500) # can use same model matrix
# 
# ggplot(train.boost$results, aes(x = n.trees, y = Rsquared, colour = as.factor(interaction.depth))) + geom_line() + 
#   ylab("CV Rsquared") + theme_bw() + theme(axis.title=element_text(size=18), axis.text=element_text(size=18)) + 
#   scale_color_discrete(name = "interaction.depth")

```

```{r}
# OSR2(pred.best.boost, test_us$suicides.100k.pop, train_us$suicides.100k.pop)
# #Out-of-sample MAE:
# sum(abs(test_us$suicides.100k.pop - pred.best.boost))/nrow(test_us_mm)
```
