---
title: "timeseries"
date: "12/18/2019"
output: pdf_document
---

```{r}
library(dplyr)
library(ggplot2)
library(lubridate)
```


# Time series
```{r}
OSR2 <- function(predictions, test, train) {
  SSE <- sum((test - predictions)^2)
  SST <- sum((test - mean(train))^2)
  r2 <- 1 - SSE/SST
  return(r2)
}
```

```{r}
# R^2 with a particular baseline
BaselineR2 <- function(predictions, truth, baseline) {
  SSE <- sum((truth - predictions)^2)
  SST <- sum((truth - baseline)^2)
  r2 <- 1 - SSE/SST
  return(r2)
}
```

```{r}
# Load data and check it out
us_ts = read.csv("us_suicides_merged_no_na.csv")
str(us_ts)
```


```{r}
# Use 2013 as testing data
train_ts <- us_ts %>% filter(year < 2010)
test_ts <- us_ts %>% filter(year >= 2010)
```



#### BUILDING MODELS:
```{r}
# Linear trend model training data -- Make a new column for the time period
# number (1, 2, ...). The dplyr syntax is a little tricky here -- n() is the
# number of rows in salesTrain, and seq_len(n()) returns the vector 1, 2, ...,
# n(). The end result is that we added a new variable called TimePeriod that
# takes values 1, 2, ..., n().
trainLM_ts<- train_ts %>% mutate(TimePeriod = seq_len(n()))
# Build and plot linear trend model
modLM <- lm(suicides.100k.pop~TimePeriod, data=trainLM_ts)
ggplot(trainLM_ts, aes(x=year, y=age)) +
  geom_line() +
  geom_point() +
  geom_line(aes(y=predict(modLM)), col="red", lwd=1.5)
```


#### Random Walk model training data 
```{r}
trainRW_ts <- train_ts %>% mutate(LastYear = c(rep(NA, 12), head(suicides.100k.pop, -12)))
head(trainRW_ts, 15)
#random walk aka moving average
```

```{r}
# Plot with an additional red line for our predictions as before
ggplot(trainRW_ts, aes(x=year, y=suicides.100k.pop)) +
  geom_line() +
  geom_point() +
  geom_line(aes(y=LastYear), col="red")
```

```{r}
# Proportion of percentages for which difference is more than 1.
table(abs(trainRW_ts$suicides.100k.pop-trainRW_ts$LastYear) >= 1)
# Compute training set R^2
# Note that we need to remove the first observation since there is no
# prediction. This is achieved using tail(.., -1) which says to take all but
# the first observation.
BaselineR2(tail(trainRW_ts$LastYear, -12), 
           tail(trainRW_ts$suicides.100k.pop, -12),
           mean(trainRW_ts$suicides.100k.pop))
```


###### AR model
```{r}
# We need to add sales yesterday and sales two days ago for the two term AR model
# head(.., -2) says take all but the last two 
trainAR_ts <- train_ts %>%
  mutate(LastYear=c(rep(NA, 12), head(suicides.100k.pop, -12))) %>%
  mutate(TwoYearsAgo = c(rep(NA, 24), head(suicides.100k.pop, -24)))
# Do the regression with one lag term
mod2a <- lm(suicides.100k.pop~LastYear, data=trainAR_ts)
summary(mod2a)
```
```{r}
# 2-term autoregressive model 
mod2b <- lm(suicides.100k.pop~LastYear+TwoYearsAgo, data=trainAR_ts)
summary(mod2b)
# Plot with an additional red line for our predictions as before
ggplot(trainAR_ts, aes(x=year, y=suicides.100k.pop)) +
  geom_line() +
  geom_point() +
  geom_line(aes(y=predict(mod2b, newdata=trainAR_ts)), col="red")
```

```{r}
## Trying Random Forest
library(randomForest)
set.seed(349)
```

```{r}
# Plug in all of the variables that we've created
mod.rf <- randomForest(suicides.100k.pop ~ LastYear + TwoYearsAgo + year, data = tail(trainAR_ts, -24))
ggplot(trainAR_ts, aes(x=year, y=suicides.100k.pop)) +
  geom_line() +
  geom_point() +
  geom_line(aes(y=predict(mod.rf, newdata=trainAR_ts)), col="green")
```

```{r}
# Both on the same plot:
ggplot(trainAR_ts, aes(x=year, y=suicides.100k.pop)) +
  geom_line() +
  geom_point() +
  geom_line(aes(y=predict(mod2b, newdata=trainAR_ts)), col="red") +
  geom_line(aes(y=predict(mod.rf, newdata=trainAR_ts)), col="green")

```

```{r}
# Create Test Set
test_ts_final <- test_ts %>%
  mutate(LastYear=c(rep(NA, 12), head(suicides.100k.pop, -12))) %>%
  mutate(TwoYearsAgo = c(rep(NA, 24), head(suicides.100k.pop, -24)))

```

```{r}
# Test set prediction and OSR^2
pred.test2 <- predict(mod2a, newdata = test_ts_final)
OSR2(tail(pred.test2, -24), trainAR_ts$suicides.100k.pop, tail(test_ts_final$suicides.100k.pop, -24))

pred.test <- predict(mod2b, newdata = test_ts_final)
OSR2(tail(pred.test, -24), trainAR_ts$suicides.100k.pop, tail(test_ts_final$suicides.100k.pop, -24))

pred.test.rf <- predict(mod.rf, newdata = test_ts_final)
OSR2(tail(pred.test.rf, -24), trainAR_ts$suicides.100k.pop, tail(test_ts_final$suicides.100k.pop, -24))

```

```{r}
# we should test with a greater fraction in test set or go with random forest maybe?

# Test set plots
ggplot(test_ts_final, aes(x=year, y=suicides.100k.pop)) +
  geom_line() +
  geom_point() +
  geom_line(aes(y=pred.test), col="red")

ggplot(test_ts_final, aes(x=year, y=suicides.100k.pop)) +
  geom_line() +
  geom_point() +
  geom_line(aes(y=pred.test), col="red") +
  geom_line(aes(y=pred.test.rf), col="green")
```







